language: python
python:
  - "3.4.5"
  - "3.5"

install:
    - pip install -r requirements.txt
    - pip install coveralls

# command to run tests
script:
    - coverage run --source=digital_milliet setup.py test

matrix:

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then coveralls; fi

branches:
  only:
    - master
    - phase2

